import {composedScenes,composedPrompt} from './composed-scene.js';
// Missing explicit ratio retains the saved job's historical contract.
export const BANNER_VIEWPORTS = [{width:1440,height:960},{width:1440,height:900},{width:1440,height:810},{width:2560,height:1080}];
export function bannerRatio(job) {
 if(composedScenes(job)&&['16:9','21:9'].includes(job.desktopAspectRatio))return job.desktopAspectRatio;
 return ['fullbleed-v2','clearance-v3'].includes(job.bannerProfile) ? '21:9' : '3:2';
}
export function bannerPrompt(job) {
 if(composedScenes(job))return composedPrompt(job,'scene-desktop',bannerRatio(job));
 if(job.bannerProfile==='clearance-v3')return `Generate a native 21:9 EMPTY ROOM background only. Remove every painting, canvas, frame, poster, mural and their shadows from the reference. Restore continuous natural plaster. Do not draw the product. Match the room materials and palette ${job.analysis.palette}; frontal wall, broad diffuse light. The program adds the artwork later. Reserved mount x20–80%, y16–66%, artwork ratio ${job.analysis.ratio}. Keep ALL central furniture and cushions below72%, with visible wall gap below66%. Side objects must not cross the central mount. Preserve plausible furniture size, move the camera or furniture rather than shrink objects. Keep top16% clear for header and bottom label area uncluttered. No text, placeholders, outlined boxes or artwork-shaped ghosts.`;
 if(job.bannerProfile !== 'fullbleed-v2')return 'Native 3:2 empty room, clear wall x28–72%, y20–70%; furniture below75%.';
 return `Create a native 21:9 EMPTY room background for a full-screen cover banner. Design the room around the accepted artwork mood, visual density and palette. Borrow suitable photographic/material cues from the reference; replace conflicting furniture, colors and composition instead of copying the room. Never stretch or blindly crop a portrait. ${job.artDirectionProfile === 'artwork-led-v1' ? 'The supplied empty room is the accepted mobile scene for this artwork. Preserve its chosen materials, palette and room design while independently recomposing camera and furniture for desktop; do not revert to the original competitor furnishings.' : ''} The accepted artwork stays separate. V2 mount x20–80%, y8–86%; calculate its actual contain-fit using the artwork ratio ${job.analysis.ratio} and the renderer before planning furniture. Keep the actual frame plus soft shadow clear. Full-screen describes the room, not a mandate to maximize the painting. Aim for balanced visual weight and breathing room. The deployed mount fixes actual artwork scale; if it overwhelms this artwork, report a layout limitation rather than shrinking furniture or pretending the prompt can resize the overlay. Keep central wall clear, tabletop/baseboard below88%; side furniture outside the actual artwork footprint. Native furniture scale, close composition, usable details in the middle 64% width; outer sides will crop at 3:2 screens. Top header and bottom product label need clear space. Neutral broad frontal/overhead diffuse light, no hard lateral beams or frame ghosts. No artwork, frame, text or logos. Palette ${job.analysis.palette}. File ratio alone does not prove acceptance: inspect complete composite at 3:2,16:10,16:9 and 2560x1080, all sale frames, including real header/label clearance.`;
}
