import {priceTable} from './product-studio/price-table.js';
import {seedModelKeys} from './test-support/studio-settings.js';
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import sharp from 'sharp';
import {Store} from './product-studio/store.js';import {Pipeline} from './product-studio/pipeline.js';import {sceneLayouts,sceneMetafields,verifySceneMetafield} from './product-studio/scene-publication.js';import {locateSceneEdges} from './product-studio/scene-edges.js';import {COMPOSED_CHECKS} from './product-studio/composed-scene.js';import {sceneHTML} from './product-studio/render.js';import {mediaSlots,mediaAlt} from './product-studio/media.js';
import {catalogTags,matchingCollections} from './product-studio/catalog-copy.js';
import {storefrontUrl} from './product-studio/store-identity.js';
import {createApp} from './product-studio/server.js';
const qa=()=>({checks:Object.fromEntries(COMPOSED_CHECKS.map(k=>[k,true])),artworkBounds:{left:.35,top:.2,right:.65,bottom:.6},objects:[],lighting:{direction:'left',softness:'soft',contactShadow:'attached',castShadow:'short'},issues:[],reason:'Frontal unframed canvas'});
async function fixture(t){const s=seedModelKeys(new Store(fs.mkdtempSync(path.join(os.tmpdir(),'scene-publish-'))));t.after(()=>fs.rmSync(s.dir,{recursive:true,force:true}));const j=s.create({target:'publish'});delete j.artDirectionProfile;j.publicationRequested=true;j.config={vision:{endpoint:'https://example.com',model:'test',apiKey:'test'},image:{endpoint:'https://example.com',model:'test',apiKey:'test'},profiles:{'3:4':{templateId:'t',referenceId:'r'}}};j.analysis={ratio:'3:4'};j.pricing={priceTableVersion:priceTable.version,variants:[]};j.copy={title:'Test',handle:'test',tags:[]};j.collections=[{id:'c'}];const art=await sharp({create:{width:300,height:400,channels:3,background:'black'}}).png().toBuffer();const room=await sharp({create:{width:1000,height:1000,channels:3,background:'white'}}).composite([{input:art,left:350,top:200}]).png().toBuffer();const master=s.addAsset(j,'master',art,{width:300,height:400,accepted:true});s.addAsset(j,'reference',art,{accepted:true});s.addAsset(j,'detail',art,{width:300,height:400,sourceHash:master.sha256,accepted:true});for(const slot of mediaSlots(j).filter(x=>x.startsWith('scene-')))s.addAsset(j,slot,room,{width:1000,height:1000,accepted:true,sceneWorkflow:j.sceneWorkflow,masterHash:master.sha256,artworkBounds:qa().artworkBounds,qa:qa()});j.selection=[1,2,3].map(i=>({file:'ref'+i+'.png'}));for(const r of j.selection)fs.writeFileSync(s.file(j.id,r.file),room);return {s,j,room};}
test('edge calibration corrects estimates but refuses featureless scenes',async()=>{const canvas=await sharp({create:{width:300,height:400,channels:3,background:'black'}}).png().toBuffer();const image=await sharp({create:{width:1000,height:1000,channels:3,background:'white'}}).composite([{input:canvas,left:350,top:200}]).png().toBuffer();const result=await locateSceneEdges(image,{left:.36,top:.21,right:.64,bottom:.59},.75);for(const [k,v] of Object.entries({left:.35,top:.2,right:.65,bottom:.6}))assert.ok(Math.abs(result.bounds[k]-v)<.003);await assert.rejects(locateSceneEdges(canvas,qa().artworkBounds,.75),/不清晰/);});
test('publication reuses all images, creates once, waits for theme and resumes without reupload',async t=>{const {s,j}=await fixture(t);let creates=0,uploads=0,publishes=0,ready=false;const product=()=>({id:'p',title:j.copy.title,handle:j.copy.handle,status:publishes?'ACTIVE':'DRAFT',onlineStoreUrl:storefrontUrl()+'products/test',sceneLayouts:{value:JSON.stringify(sceneLayouts(j))},variants:{nodes:[],pageInfo:{}},media:{nodes:mediaSlots(j).map(slot=>({alt:mediaAlt(slot,j),status:'READY',image:s.active(j,slot)})),pageInfo:{}},collections:{nodes:[{id:'c'}],pageInfo:{}},resourcePublications:{nodes:publishes?[{isPublished:true,publication:{name:'Online Store'}}]:[],pageInfo:{}}});const shop={pricing:async()=>j.pricing,find:async()=>[],create:async()=>{creates++;return 'p';},upload:async()=>uploads++,product:async()=>product(),verifyMediaProfile:async()=>{if(!ready)throw Error('Wait for theme');},publish:async()=>publishes++};const p=new Pipeline(s,shop,{vision:async()=>assert.fail('No repeat analysis'),generate:async()=>assert.fail('No image generation')});p.make=async()=>{};await p.run(j);assert.equal(j.status,'awaiting-theme');assert.equal(creates,1);assert.equal(uploads,1);assert.equal(publishes,0);const fields=sceneMetafields(j);assert.equal(fields.length,1);verifySceneMetafield(j,product());assert.throws(()=>verifySceneMetafield(j,{sceneLayouts:{value:'{}'}}),/回读/);ready=true;await p.run(j);assert.equal(j.status,'published');assert.equal(creates,1);assert.equal(uploads,1);assert.equal(publishes,1);});
test('mapped complete scenes render exactly one original image with rails only',async t=>{const {s,j,room}=await fixture(t);for(const slot of mediaSlots(j).filter(x=>x.startsWith('scene-'))){const a=s.active(j,slot);a.frameMapping={...await locateSceneEdges(room,a.artworkBounds,.75),sourceHash:a.sha256};}for(const frame of ['Oak','Black','Walnut','White','Gold','Silver']){const html=await sceneHTML(s,j,'scene-1',frame+' Float Frame');assert.equal((html.match(/<img /g)||[]).length,1);assert.match(html,/data-composed-frame/);assert.match(html,new RegExp('data-frame="'+frame.toLowerCase()+'"'));assert.doesNotMatch(html,/frame-art-image/);}const a=s.active(j,'scene-1');a.frameMapping.sourceHash='stale';assert.throws(()=>sceneLayouts(j),/尚未核准/);});
test('publication action queues a completed scene job, rejects missing media, and new jobs retain automation',async t=>{const {s,j}=await fixture(t);assert.equal(s.create({target:'publish'}).publicationRequested,true);j.status='scenes-ready';j.publicationRequested=false;s.save(j);const app=createApp({store:s,shopify:{configured:()=>true},pipeline:{recover(){},tick(){}}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>app.server.close());const base='http://127.0.0.1:'+app.server.address().port;const {token}=await(await fetch(base+'/api/bootstrap')).json();const post=()=>fetch(base+'/api/jobs/'+j.id+'/publish',{method:'POST',headers:{'X-Studio-Token':token,'Content-Type':'application/json'},body:'{}'});let response=await post();assert.equal(response.status,200);assert.equal(s.get(j.id).publicationRequested,true);j.status='scenes-ready';s.active(j,'scene-1').accepted=false;s.save(j);response=await post();assert.equal(response.status,400);assert.equal(s.get(j.id).status,'scenes-ready');});
test('copy uses actual taxonomy tags and collection rules rather than singular/plural handle guesses',()=>{const collection=(handle,tag)=>({handle,ruleSet:{rules:[{column:'TAG',relation:'EQUALS',condition:tag}],appliedDisjunctively:false}});const all=[{handle:'all-products'},collection('landscapes','subject-landscapes'),collection('figurative','subject-figurative'),collection('abstract','subject-abstract'),collection('new-arrivals','new-arrival')];assert.deepEqual(catalogTags(all),['subject-landscapes','subject-figurative','subject-abstract']);assert.deepEqual(matchingCollections(all,['subject-figurative','new-arrival']).map(c=>c.handle),['all-products','figurative','new-arrivals']);});
