import {priceTable} from './product-studio/price-table.js';
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import sharp from 'sharp';
import {mediaSlots,mediaAlt} from './product-studio/media.js';
import {Store,atomic} from './product-studio/store.js';
import {Pipeline} from './product-studio/pipeline.js';
import {createApp} from './product-studio/server.js';
import {UncertainError} from './product-studio/providers.js';
import {sceneScreenshot} from './product-studio/render.js';
import {acquireLock} from './product-studio/lock.js';

async function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'canvasra-studio-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const s=new Store(dir);const png=await sharp({create:{width:300,height:400,channels:3,background:'#b3a18f'}}).png().toBuffer();const c=s.settings();c.backgroundCheck=false;c.vision=c.image={endpoint:'https://example.com/api',model:'test',apiKey:'SECRET'};c.profiles={'3:4':{templateId:'t',referenceId:'r'}};c.libraryRoot=path.join(dir,'library');fs.mkdirSync(path.join(c.libraryRoot,'Bigsize'),{recursive:true});for(const f of ['one.png','two.png','Bigsize/three.png'])fs.writeFileSync(path.join(c.libraryRoot,f),png);atomic(path.join(dir,'settings.json'),c);const j=s.create({});delete j.mediaProfile;delete j.mobileSceneProfile;delete j.bannerProfile;delete j.sceneWorkflow;delete j.artDirectionProfile;s.addAsset(j,'reference',png,{width:300,height:400,accepted:true});return {s,j,png};}
test('studio pipeline completes with injected providers, preserves source detail and only creates once',async t=>{const {s,j,png}=await fixture(t);let creates=0;const shop={catalog:async()=>({}),pricing:async()=>({variants:[]}),collections:async()=>[{id:'c',handle:'all-products'}],find:async()=>[],create:async()=>{creates++;return 'p';},upload:async()=>{},product:async()=>({id:'p',title:j.copy.title,handle:j.copy.handle,variants:{nodes:[],pageInfo:{}},media:{nodes:['master','detail','scene-1','scene-2','scene-3'].map(slot=>({status:'READY',alt:mediaAlt(slot),image:s.active(j,slot)})),pageInfo:{}},collections:{nodes:[{id:'c'}],pageInfo:{}},resourcePublications:{nodes:[],pageInfo:{}}})};const ai=async(c,p)=>({data:p.startsWith('Analyze')?{title:'Test',ratio:'3:4',palette:'warm',masterPrompt:'Artwork'}:p.startsWith('Choose')?{indices:[1,2,3]}:p.startsWith('Write')?{title:'Test',handle:'test',paragraphs:['<test>'],tags:[]}:{pass:true,issues:[],reason:'Accepted'},usage:null});const worker=new Pipeline(s,shop,{vision:ai,generate:async()=>({bytes:png}),render:async()=>png});await worker.run(j);assert.equal(j.status,'draft');assert.equal(creates,1);assert.equal(s.active(j,'detail').sourceHash,s.active(j,'master').sha256);assert.match(j.copy.descriptionHtml,/&lt;test&gt;/);await worker.run(j);assert.equal(creates,1);assert.equal(j.assets.master.length,1);});
test('uncertain generation never runs again automatically',async t=>{const {s,j}=await fixture(t);j.status='queued';j.analysis={ratio:'3:4',texture:false,masterPrompt:'art'};j.pricing={priceTableVersion:priceTable.version,variants:[]};s.save(j);let count=0;const p=new Pipeline(s,{}, {generate:async()=>{count++;throw new UncertainError('uncertain');}});await p.tick();assert.equal(s.get(j.id).status,'uncertain');await p.tick();assert.equal(count,1);});
test('create mode demands an original composition while extract mode preserves the reference',async t=>{
 const {s,j,png}=await fixture(t);const prompts={};
 const shopFor=job=>({catalog:async()=>({}),pricing:async()=>({variants:[]}),collections:async()=>[{id:'c',handle:'all-products'}],find:async()=>[],create:async()=>'p',upload:async()=>{},product:async()=>({id:'p',title:job.copy.title,handle:job.copy.handle,variants:{nodes:[],pageInfo:{}},media:{nodes:['master','detail','scene-1','scene-2','scene-3'].map(slot=>({status:'READY',alt:mediaAlt(slot),image:s.active(job,slot)})),pageInfo:{}},collections:{nodes:[{id:'c'}],pageInfo:{}},resourcePublications:{nodes:[],pageInfo:{}}})});
 const ai=job=>async(c,p)=>{if(p.startsWith('Analyze'))prompts[job.id+'-analyze']=p;return {data:p.startsWith('Analyze')?{title:'Test',ratio:'3:4',palette:'warm',masterPrompt:'Artwork'}:p.startsWith('Choose')?{indices:[1,2,3]}:p.startsWith('Write')?{title:'Test',handle:'test',paragraphs:['x'],tags:[]}:{pass:true,issues:[],reason:'Accepted'}};};
 const gen=job=>async(c,p)=>{if(!prompts[job.id+'-master']&&p.includes('unframed artwork'))prompts[job.id+'-master']=p;return {bytes:png};};
 await new Pipeline(s,shopFor(j),{vision:ai(j),generate:gen(j),render:async()=>png}).run(j);assert.equal(j.status,'draft');
 assert.match(prompts[j.id+'-analyze'],/clearly different original artwork/);assert.match(prompts[j.id+'-master'],/different composition, viewpoint, element arrangement/);assert.doesNotMatch(prompts[j.id+'-master'],/Faithfully preserve/);assert.doesNotMatch(prompts[j.id+'-master'],/never crop, trim or omit any edge content/);
 const j2=s.create({mode:'extract'});delete j2.mediaProfile;delete j2.mobileSceneProfile;delete j2.bannerProfile;delete j2.sceneWorkflow;delete j2.artDirectionProfile;s.addAsset(j2,'reference',png,{width:300,height:400,accepted:true});
 await new Pipeline(s,shopFor(j2),{vision:ai(j2),generate:gen(j2),render:async()=>png}).run(j2);assert.equal(j2.status,'draft');
 assert.doesNotMatch(prompts[j2.id+'-analyze'],/clearly different original artwork/);assert.match(prompts[j2.id+'-master'],/Faithfully preserve the supplied artwork/);assert.match(prompts[j2.id+'-master'],/never crop, trim or omit any edge content/);assert.doesNotMatch(prompts[j2.id+'-master'],/different composition, viewpoint/);
});
test('server hides credentials, blocks non-image files and CSRF writes',async t=>{const {s,j}=await fixture(t);j.config=s.settings();s.save(j);const app=createApp({store:s,shopify:{configured:()=>false},pipeline:{recover(){},tick(){}}});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>app.server.close(r)));const base='http://127.0.0.1:'+app.server.address().port;const res=await fetch(base+'/api/bootstrap'),text=await res.text();assert.ok(!text.includes('SECRET'));assert.equal((await fetch(base+'/media/'+j.id+'/job.json')).status,404);assert.equal((await fetch(base+'/api/jobs',{method:'POST',body:'{}'})).status,403);});
test('pause request takes effect at the next checkpoint',async t=>{const {s,j}=await fixture(t);const p=new Pipeline(s,{});atomic(path.join(s.jobDir(j.id),'pause.json'),{requested:true});await assert.rejects(()=>p.step(j,'test',async()=>{}));assert.equal(s.get(j.id).status,'paused');});
test('actual theme scene renders a non-empty 3:4 preview',async t=>{const {s,j,png}=await fixture(t);s.addAsset(j,'master',png,{width:300,height:400,accepted:true});s.addAsset(j,'scene-3',png,{width:300,height:400,accepted:true});const output=await sceneScreenshot(s,j,'scene-3');const m=await sharp(output).metadata();assert.equal(m.width,750);assert.equal(m.height,1000);const stats=await sharp(output).stats();assert.ok(stats.channels[0].stdev>3,'frame must be visibly rendered');});
test('a second worker cannot claim the same directory',async t=>{const {s}=await fixture(t);const release=acquireLock(s.dir);t.after(release);assert.throws(()=>acquireLock(s.dir),/已有/);});

test('new jobs require one additional desktop room; legacy jobs retain their original media count',async t=>{const {s}=await fixture(t);const j=s.create({});assert.equal(j.mediaProfile,'responsive-v1');assert.equal(j.mobileSceneProfile,'clearance-v2');assert.equal(mediaAlt('scene-3',j),'composed-unframed-scene-3-v1');assert.equal(mediaAlt('scene-3',{...j,sceneWorkflow:'lighting-v1'}),'scene-room-large-v2');assert.equal(mediaAlt('scene-3'),'scene-room-large-v1');assert.equal(mediaSlots(j).length,6);j.analysis={texture:true};assert.equal(mediaSlots(j).length,6);j.productId='historical';delete j.textureWorkflow;assert.equal(mediaSlots(j).length,7);delete j.mediaProfile;assert.equal(mediaSlots(j).length,6);assert.equal(mediaAlt('scene-desktop'),'scene-room-desktop-v1');});

test('responsive pipeline generates both ratios and validates all six uploads',async t=>{const {s,j,png}=await fixture(t);j.mediaProfile='responsive-v1';j.analysis={title:'Test',ratio:'3:4',palette:'warm',texture:true,masterPrompt:'Artwork'};j.delivery='all';let creates=0;const shop={verifyMediaProfile:async()=>{},catalog:async()=>({}),pricing:async()=>({variants:[]}),collections:async()=>[{id:'c',handle:'all-products'}],find:async()=>[],create:async()=>{creates++;return 'p';},upload:async()=>{},product:async()=>({id:'p',title:j.copy.title,handle:j.copy.handle,variants:{nodes:[],pageInfo:{}},media:{nodes:mediaSlots(j).map(slot=>({status:'READY',alt:mediaAlt(slot),image:s.active(j,slot)})),pageInfo:{}},collections:{nodes:[{id:'c'}],pageInfo:{}},resourcePublications:{nodes:[],pageInfo:{}}})};const ai=async(c,p)=>({data:p.startsWith('Analyze')?{title:'Test',ratio:'3:4',palette:'warm',masterPrompt:'Artwork'}:p.startsWith('Choose')?{indices:[1,2,3]}:p.startsWith('Write')?{title:'Test',handle:'test',paragraphs:['<test>'],tags:[]}:{pass:true,issues:[],reason:'Accepted'},usage:null});const worker=new Pipeline(s,shop,{vision:ai,generate:async(c,p,ratio)=>{const [w,h]=ratio.split(':').map(Number);return {bytes:await sharp({create:{width:w*100,height:h*100,channels:3,background:'#b3a18f'}}).png().toBuffer()};},render:async()=>png});await worker.run(j);assert.equal(j.status,'draft');assert.equal(creates,1);assert.equal(s.active(j,'detail').sourceHash,s.active(j,'master').sha256);assert.match(j.copy.descriptionHtml,/&lt;test&gt;/);await worker.run(j);assert.equal(creates,1);assert.equal(j.assets.master.length,1);});


test('artwork-led pipeline persists directions and reference choices, skips AI review, and resumes without regeneration',async t=>{
 const {s,j,png}=await fixture(t);Object.assign(j,{artDirectionProfile:'artwork-led-v1',bannerProfile:'fullbleed-v2',mediaProfile:'responsive-v1',sceneWorkflow:'lighting-v1'});
 const {DIRECTION_FIELDS,AESTHETIC_CHECKS}=await import('./product-studio/art-direction.js');const {SCENE_CHECKS}=await import('./product-studio/scene-quality.js');
 const variants=[{size:'30 × 40 cm',frame:'Oak Float Frame',price:'105.00',inventoryPolicy:'CONTINUE'}];let generated=0;let selected=false;
 const shop={verifyMediaProfile:async()=>{},catalog:async()=>({}),pricing:async()=>({variants}),collections:async()=>[{id:'c',handle:'all-products'}],find:async()=>[],create:async()=> 'p',upload:async()=>{},product:async()=>({id:'p',title:j.copy.title,handle:j.copy.handle,variants:{nodes:variants.map(v=>({...v,availableForSale:true,selectedOptions:[{name:'Size',value:v.size},{name:'Frame',value:v.frame}]})),pageInfo:{}},media:{nodes:mediaSlots(j).map(slot=>({status:'READY',alt:mediaAlt(slot,j),image:s.active(j,slot)})),pageInfo:{}},collections:{nodes:[{id:'c'}],pageInfo:{}},resourcePublications:{nodes:[],pageInfo:{}}})};
 const vision=async(c,p,images)=>{let data;
 if(p.startsWith('Analyze'))data={title:'Blue cats',ratio:'3:4',palette:'blue',texture:false,masterPrompt:'Cats'};
 else if(p.startsWith('Design three'))data={artworkReading:'Light playful blue cats',scenes:[1,2,3].map(i=>({slot:'scene-'+i,...Object.fromEntries(DIRECTION_FIELDS.map(k=>[k,k+' specific '+i]))}))};
 else if(p.startsWith('Choose'))data={indices:[1,2,3],reason:'Artwork fit'};
 else if(p.startsWith('Select exactly')){selected=true;data={scenes:[1,2,3].map((i)=>({slot:'scene-'+i,index:[2,3,1][i-1],reason:'Fits artwork',keep:'Diffuse plaster light',discard:'Heavy leather'}))};}
 else if(p.startsWith('Plan'))assert.fail('No review planning'); else if(false)data={lightSource:'Broad frontal light',shadowDirection:'Down',softness:'Diffuse',wallPerspective:'Frontal',sharpness:'Coherent',adaptation:'Light furniture',compatible:true};
 else if(p.startsWith('Write'))data={title:'Blue cats',handle:'blue-cats',paragraphs:['Blue cats'],tags:[]};
 else assert.fail('Unexpected AI review call: '+p);return {data};};
 const views=n=>async()=>Array.from({length:n},(_,i)=>({viewport:{width:400+i,height:600},geometry:{},pass:true,bytes:png}));
 const worker=new Pipeline(s,shop,{vision,generate:async(c,p,r)=>{generated++;if(p.includes('EMPTY'))assert.match(p,/Mandatory artwork direction/);const [w,h]=r.split(':').map(Number);return {bytes:await sharp({create:{width:w*100,height:h*100,channels:3,background:'#aaa'}}).png().toBuffer()};},render:async()=>png,bannerRender:views(4),mobileRender:views(2)});
 await worker.run(j);assert.equal(j.status,'draft');assert.ok(selected);assert.equal(j.artDirection.masterHash,s.active(j,'master').sha256);assert.ok(fs.existsSync(s.file(j.id,'scene-art-direction.json')));assert.equal(j.selection[0].discard,'Heavy leather');assert.equal(s.active(j,'scene-3').qa,undefined);assert.equal(s.active(j,'scene-desktop').qa,undefined);const calls=generated;await worker.run(j);assert.equal(generated,calls);
});
